name: stock_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^0.13.6
  provider: ^6.1.5
  shared_preferences: ^2.1.1
  fl_chart: ^0.63.0   # jika error, ganti ke 0.63.0 atau upgrade Flutter SDK
  intl: ^0.18.0
  logger: ^2.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  #assets:
   #- assets/images/
   #- assets/json/