name: Auto Retrain Model Weekly

on:
  schedule:
    - cron: "0 0 * * 0"  # setiap minggu (Minggu pukul 00:00 UTC)
  workflow_dispatch:      # bisa juga kamu jalankan manual dari GitHub Actions

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout Repository
        uses: actions/checkout@v4

      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: 📦 Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🧠 Train Model
        run: |
          cd backend
          python train_realtime_safe.py

      - name: 💾 Commit Updated Model
        run: |
          cd backend
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add stock_model.keras
          git commit -m "🤖 Auto retrain model on $(date)"
          git push
        continue-on-error: true  # biar workflow tetap lanjut kalau tidak ada perubahan
